### ISSUE TITLE
添加 syn-sys-fe

### ISSUE THREAD

**Issue by SkyeYoung** [JUST-NC/syn-sys#3]
@thredreams @Chever-John 

已经把 https://github.com/JUST-NC/syn-sys-fe 迁移到这个帐号了。

有啥问题先去找 @uniqie ，他能解决大部分问题，需要补什么页面也是，我暂时有点忙。

目前这个仓库里的 https://github.com/JUST-NC/syn-sys/blob/master/fe.Dockerfile 指的是 ruoyi 的前端部分，可以改一个名字，比如 beFe 啥的。然后再照着这个写 syn-sys-fe 的 dockerfile。

注意，最好把下面这一行中的镜像源改成 https://npmmirror.com/ 的：
 https://github.com/JUST-NC/syn-sys/blob/2c15a696dc59679228f34eef1ff01cfd5b40c092/fe.Dockerfile#L4 

其他需要的改的应该就一个 https://github.com/JUST-NC/syn-sys/blob/master/docker-compose.yml ，nginx 那边应该没有问题。

修改完成后再提交一下，防止后面再丢了。

**Comment by uniqie** [comment]
？

**Comment by Chever-John** [comment]
Just find it! Wow
